version: '3.8'
name: formation_symfony_6_intermediate
services:
  web:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./src/public:/var/www/html/public:delegated
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - symfony_net
  php:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - DOCKER_BUILDKIT=1
    container_name: symfony_php
    volumes:
      - ./src:/var/www/html:delegated
      - ./.php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - symfony_app_var:/var/www/html/var
      - symfony_app_vendor:/var/www/html/vendor
    networks:
      - symfony_net
    depends_on:
      - database
    command: php-fpm
  node:
    image: node:18
    container_name: symfony_node
    volumes:
      - ./src:/var/www/html:delegated
      - node_modules:/var/www/html/node_modules:delegated
    working_dir: /var/www/html
    networks:
      - symfony_net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    command: [ "tail", "-f", "/dev/null" ]
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - symfony_net
    ports:
      - "5464:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
volumes:
  database_data:
  node_modules:
  symfony_app_var:
  symfony_app_vendor:
networks:
  symfony_net:
