version: '3.8'
name: formation_symfony_6
services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: symfony_php_intermediate
    volumes:
      - .:/var/www/html:cached
    networks:
      - symfony_net

  web:
    image: nginx:alpine
    container_name: symfony_nginx_intermediate
    volumes:
      - .:/var/www/html:cached
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - symfony_net

  node:
    image: node:18
    container_name: symfony_node_intermediate
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony_net
    command: [ "tail", "-f", "/dev/null" ]
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: symfony_db_intermediate
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - symfony_net
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
    ###< doctrine/doctrine-bundle ###

networks:
  symfony_net:
